# Generated by Django 5.2.12 on 2026-05-14 03:19

import apps.schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('verify_job_status', 'verify_job_status'), ('extract_job_dates', 'extract_job_dates')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('batch_size', models.IntegerField(default=100)),
                ('batches_per_day', models.IntegerField(default=2)),
                ('hours_utc', models.JSONField(default=apps.schedule.models._default_hours)),
                ('use_no_auth_check', models.BooleanField(default=False)),
                ('platform', models.CharField(default='linkedin', max_length=32)),
                ('current_run_pid', models.IntegerField(blank=True, null=True)),
                ('current_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_run_log_path', models.CharField(blank=True, default='', max_length=500)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verifier_schedules',
                'ordering': ['command'],
            },
        ),
    ]
