# Generated by Django 5.2.12 on 2026-05-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifierschedule',
            name='headless',
            field=models.BooleanField(default=True),
        ),
    ]
