# Generated by Django 5.2.12 on 2026-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_verifierschedule_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifierschedule',
            name='command',
            field=models.CharField(choices=[('verify_job_status', 'verify_job_status'), ('extract_job_dates', 'extract_job_dates'), ('morning_refresh', 'morning_refresh'), ('poll_mail_replies', 'poll_mail_replies')], max_length=32, unique=True),
        ),
    ]
