# Generated by Django 5.2.12 on 2026-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_humanlabel_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairqueue',
            name='selection_reason',
            field=models.CharField(choices=[('medium_overlap', 'Medium Overlap'), ('high_overlap', 'High Overlap'), ('hard_negative', 'Hard Negative'), ('random', 'Random'), ('cross_domain_hard_neg', 'Cross-Domain Hard Negative'), ('related_skill_positive', 'Related-Skill Positive'), ('seniority_hard_neg', 'Seniority Hard Negative'), ('missing_must_have', 'Missing Must-Have'), ('boundary_medium', 'Boundary Medium')], max_length=30),
        ),
    ]
