# Generated by Django 5.2.12 on 2026-05-22 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_daily_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
