# Generated by Django 5.2.12 on 2026-06-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_employeejobmatch_score_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Outgoing'), ('in', 'Incoming')], max_length=3)),
                ('from_addr', models.EmailField(max_length=254)),
                ('to_addr', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('message_id', models.TextField(db_index=True)),
                ('in_reply_to', models.TextField(blank=True, db_index=True, default='')),
                ('is_bounce', models.BooleanField(default=False)),
                ('cv_attached', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employees.employee')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='employees.employeejobmatch')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_address', models.EmailField(max_length=254, unique=True)),
                ('password_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error')], default='active', max_length=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_credential', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_mail_credentials',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mail_reply', 'Mail reply'), ('mail_bounce', 'Mail bounce')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body_preview', models.TextField(blank=True, default='')),
                ('link_url', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
