# Generated by Django 5.2.12 on 2026-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemailcredential',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
