# Generated by Django 5.2.12 on 2026-05-22 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0008_verifier_run_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='employee_cvs/')),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('is_parse_failed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('bench', 'On bench'), ('pursuing', 'Pursuing'), ('placed', 'Placed'), ('inactive', 'Inactive')], db_index=True, default='bench', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('pursuing', 'Pursuing'), ('applied', 'Applied'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='suggested', max_length=15)),
                ('match_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matches', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='employees.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_matches', to='jobs.job')),
            ],
            options={
                'db_table': 'employee_job_matches',
                'ordering': ['-match_score', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', '-created_at'], name='employees_status_95af7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email',), name='uniq_employee_email_nonblank'),
        ),
        migrations.AddIndex(
            model_name='employeejobmatch',
            index=models.Index(fields=['employee', 'status', '-match_score'], name='employee_jo_employe_1a6569_idx'),
        ),
        migrations.AddIndex(
            model_name='employeejobmatch',
            index=models.Index(fields=['status', '-updated_at'], name='employee_jo_status_eba661_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeejobmatch',
            constraint=models.UniqueConstraint(fields=('employee', 'job'), name='uniq_emp_job'),
        ),
    ]
