# Generated by Django 5.2.12 on 2026-06-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobmatch',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeejobmatch',
            name='seniority_gap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
