# Generated by Django 5.2.12 on 2026-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeejobmatch_missing_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobmatch',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('pursuing', 'Pursuing'), ('applied', 'Applied'), ('won', 'Won'), ('lost', 'Lost'), ('dismissed', 'Not a fit')], db_index=True, default='suggested', max_length=15),
        ),
    ]
