# Generated by Django 5.2.12 on 2026-06-09 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeejobmatch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_status_95af7c_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='employees_created_d894c4_idx'),
        ),
    ]
