# Generated by Django 5.2.12 on 2026-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_employees_status_95af7c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobmatch',
            name='dim_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
