# Generated by Django 5.2.12 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeejobmatch_dim_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobmatch',
            name='covered_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
