# Generated by Django 5.2.12 on 2026-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeejobmatch_covered_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobmatch',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
