# Generated by Django 5.2.12 on 2026-06-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeejobmatch_score_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='employee_cvs/')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('seniority', models.IntegerField(choices=[(0, 'Intern'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=2)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('is_parse_failed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_cvs',
                'ordering': ['-is_active', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='uniq_active_cv_per_employee')],
            },
        ),
    ]
