# Generated by Django 5.2.12 on 2026-06-30 04:45

from django.db import migrations, models
from django.db.models import F


def backfill_matched_at(apps, schema_editor):
    """Existing parsed employees have already been ranked — stamp matched_at
    (= parsed_at) so they don't read as 'ranking in progress'."""
    Employee = apps.get_model("employees", "Employee")
    Employee.objects.filter(parsed_at__isnull=False, matched_at__isnull=True).update(matched_at=F("parsed_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_backfill_active_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_matched_at, migrations.RunPython.noop),
    ]
