# Generated by Django 5.2.12 on 2026-05-13 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_job_role_category_and_experience'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('expired', 'Expired'), ('unverified', 'Unverified')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='verification_backoff_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['platform', 'lifecycle'], name='jobs_platform_lifecycle_idx'),
        ),
        # Backfill last_seen_at = created_at for pre-existing rows (data-model.md).
        migrations.RunSQL(
            sql="UPDATE jobs SET last_seen_at = created_at WHERE last_seen_at IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
