# Generated by Django 5.2.12 on 2026-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('verify_job_status', 'verify_job_status'), ('extract_job_dates', 'extract_job_dates')], db_index=True, max_length=32)),
                ('platform', models.CharField(db_index=True, max_length=32)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField()),
                ('batch_size_requested', models.IntegerField()),
                ('total_examined', models.IntegerField()),
                ('skipped_unsupported_url', models.IntegerField(default=0)),
                ('counts_by_outcome', models.JSONField(default=dict)),
                ('session_expired_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'verifier_run_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['command', 'started_at'], name='verifier_run_cmd_time_idx')],
            },
        ),
    ]
