# Generated by Django 5.2.12 on 2026-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_verifier_run_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_usd_annual_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_usd_annual_min',
            field=models.IntegerField(default=0),
        ),
    ]
