# Generated by Django 5.2.12 on 2026-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True)),
                ('config_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error')], default='connected', max_length=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['platform'],
            },
        ),
    ]
