# Generated by Django 5.2.12 on 2026-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='events',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
